[project]
name = "django-socio-grpc-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-socio-grpc>=0.24.3",
]
